name: RDP-client-win11-arm

on:
  workflow_dispatch:

jobs:
  rdp-session:
    runs-on: windows-latest
    timeout-minutes: 360 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup RDP User and Service
        env:
          RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        shell: pwsh
        run: |
          if (-not $env:RDP_USERNAME -or -not $env:RDP_PASSWORD) {
            Write-Error "RDP_USERNAME and RDP_PASSWORD secrets must be set in repository settings."
            exit 1
          }

          # Create and configure the user
          $username = $env:RDP_USERNAME
          $password = ConvertTo-SecureString -String $env:RDP_PASSWORD -AsPlainText -Force
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Write-Host "User '$username' already exists. Setting new password."
            Set-LocalUser -Name $username -Password $password
          } else {
            Write-Host "Creating new user '$username'."
            New-LocalUser -Name $username -Password $password -FullName "RDP User"
            Set-LocalUser -Name $username -PasswordNeverExpires $true
          }
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Write-Host "User '$username' configured for RDP and administrator access."

          # Enable RDP and configure firewall
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "RDP service and firewall have been configured."

      - name: Connect via Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: gh-runner-win-arm

      - name: Wait for RDP Connection
        shell: pwsh
        run: |
          Write-Host "The runner is ready for an RDP connection."
          Write-Host "This job will remain active for up to 6 hours."
          Start-Sleep -Seconds 21600
