name: RDP-client without docker

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                            -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                            -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                            -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create or update RDP user from secrets (secure)
        env:
          RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          if (-not $env:RDP_USERNAME -or -not $env:RDP_PASSWORD) {
              Write-Error "RDP_USERNAME and/or RDP_PASSWORD secrets are not set."
              exit 1
          }

          $username = $env:RDP_USERNAME
          $plain = $env:RDP_PASSWORD

          $securePass = ConvertTo-SecureString $plain -AsPlainText -Force

          try {
              if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
                  Set-LocalUser -Name $username -Password $securePass -ErrorAction Stop
              } else {
                  New-LocalUser -Name $username -Password $securePass -AccountNeverExpires -ErrorAction Stop
              }

              Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username -ErrorAction Stop
              Add-LocalGroupMember -Group "Administrators" -Member $username -ErrorAction SilentlyContinue
          } catch {
              Write-Error "Failed to create or update local user: $_"
              exit 1
          } finally {
              # Clear plaintext password variable ASAP
              $plain = $null
              [System.GC]::Collect()
              [System.GC]::WaitForPendingFinalizers()
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale connection and verify RDP port
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          if (-not $env:TAILSCALE_AUTH_KEY) {
              Write-Error "TAILSCALE_AUTH_KEY secret is not set."
              exit 1
          }

          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=gh-runner-$env:GITHUB_RUN_ID

          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }

          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }

          $testResult = Test-NetConnection -ComputerName $tsIP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }

      - name: Download and silent-install MEmu (uses /S)
        run: |
          # WARNING: GitHub-hosted Windows runners may not support virtualization or GUI installs required by Android emulators.
          $memuUrl = "https://www.memuplay.com/download-memu-on-pc.html?from=online2_installer"
          $installer = "$env:TEMP\MEmuOnlineInstaller.exe"
          $log = "$env:TEMP\memu_install.log"

          Write-Host "Downloading MEmu installer from $memuUrl to $installer"
          try {
              Invoke-WebRequest -Uri $memuUrl -OutFile $installer -UseBasicParsing -ErrorAction Stop
              if (-not (Test-Path $installer)) {
                  Write-Error "Download completed but file not found at $installer"
                  exit 1
              }
              Write-Host "Download successful: $(Get-Item $installer | Select-Object FullName, Length)"
          } catch {
              Write-Error "Failed to download MEmu installer: $_"
              exit 1
          }

          Write-Host "Attempting silent install with the /S flag (single attempt only). Output logged to $log"
          try {
              Start-Process -FilePath $installer -ArgumentList "/S" -Wait -NoNewWindow -PassThru *>&1 | Tee-Object -FilePath $log
              $exit = $LASTEXITCODE
              Write-Host "Installer exited with code $exit"
          } catch {
              Write-Error "Silent install attempt threw an exception: $_"
              exit 1
          }

          if ($exit -ne 0) {
              Write-Error "Installer returned non-zero exit code ($exit). Check $log for details and consider using a self-hosted runner."
              exit $exit
          }

          # Basic heuristic checks for install artifacts
          $installed = $false
          $possiblePaths = @(
              "$env:ProgramFiles\Microvirt\MEmu",
              "$env:ProgramFiles(x86)\Microvirt\MEmu",
              "$env:ProgramFiles\MEmu",
              "$env:ProgramFiles(x86)\MEmu"
          )
          foreach ($p in $possiblePaths) {
              if (Test-Path $p) {
                  Write-Host "Found possible installation directory: $p"
                  $installed = $true
                  break
              }
          }

          $proc = Get-Process -Name "dnplayer" -ErrorAction SilentlyContinue
          if ($proc) {
              Write-Host "Detected emulator process: $($proc.Id)"
              $installed = $true
          }

          if (-not $installed) {
              Write-Warning "No obvious installation artifacts found after /S install. Installation may require a GUI or virtualization; consider using a self-hosted runner."
          } else {
              Write-Host "MEmu appears to be installed or running."
          }

      - name: Notify Discord that RDP client is active (optional)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          function Send-DiscordMessage($message) {
              if (-not $env:DISCORD_WEBHOOK) {
                  Write-Host "DISCORD_WEBHOOK not set; skipping Discord notification."
                  return
              }
              $payload = @{ content = $message } | ConvertTo-Json -Compress
              try {
                  Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -ContentType 'application/json' -Body $payload -ErrorAction Stop
              } catch {
                  Write-Error "Failed to send Discord message: $_"
              }
          }

          # Only send a minimal non-sensitive message; skip if webhook is not configured.
          Send-DiscordMessage "rdp-client active"

      - name: Maintain connection and periodic heartbeat (Discord optional)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          function Send-DiscordMessage($message) {
              if (-not $env:DISCORD_WEBHOOK) {
                  Write-Host "DISCORD_WEBHOOK not set; skipping Discord heartbeat."
                  return
              }
              $payload = @{ content = $message } | ConvertTo-Json -Compress
              try {
                  Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -ContentType 'application/json' -Body $payload -ErrorAction Stop
              } catch {
                  Write-Error "Failed to send Discord message: $_"
              }
          }

          while ($true) {
              Send-DiscordMessage "rdp-client active"
              Start-Sleep -Seconds 300
          }